import "bootstrap/dist/css/bootstrap.css";
import type { Metadata } from "next";
import { Bricolage_Grotesque, Gochi_Hand } from "next/font/google";
import AuthProvider from "./auth/Provider";
import BootstrapClient from "./BootstrapClient";
import "./globals.css";
import Navbar from "./Navbar";
import QueryClientProvider from "./QueryClientProvider";

const brico = Bricolage_Grotesque({
  subsets: ["latin"],
});

const gochi = Gochi_Hand({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gochi.className}`}>
        <QueryClientProvider>
          <AuthProvider>
            <Navbar />
            {children}
            <BootstrapClient />
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
